"""add_inflow_webhooks_table

Revision ID: 8c142b1fbf6c
Revises: d23def0cc9a5
Create Date: 2025-12-18 13:42:23.653955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c142b1fbf6c'
down_revision: Union[str, None] = 'd23def0cc9a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inflow_webhooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('webhook_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'FAILED', name='webhookstatus'), nullable=False),
    sa.Column('last_received_at', sa.DateTime(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('secret', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inflow_webhooks_status'), 'inflow_webhooks', ['status'], unique=False)
    op.create_index(op.f('ix_inflow_webhooks_webhook_id'), 'inflow_webhooks', ['webhook_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inflow_webhooks_webhook_id'), table_name='inflow_webhooks')
    op.drop_index(op.f('ix_inflow_webhooks_status'), table_name='inflow_webhooks')
    op.drop_table('inflow_webhooks')
    # ### end Alembic commands ###
