"""Initial migration

Revision ID: d23def0cc9a5
Revises: 
Create Date: 2025-12-17 21:45:19.798472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd23def0cc9a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inflow_order_id', sa.String(), nullable=False),
    sa.Column('inflow_sales_order_id', sa.String(), nullable=True),
    sa.Column('recipient_name', sa.String(), nullable=True),
    sa.Column('recipient_contact', sa.String(), nullable=True),
    sa.Column('delivery_location', sa.String(), nullable=True),
    sa.Column('po_number', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'PRE_DELIVERY', 'IN_DELIVERY', 'DELIVERED', 'ISSUE', name='orderstatus'), nullable=False),
    sa.Column('assigned_deliverer', sa.String(), nullable=True),
    sa.Column('issue_reason', sa.Text(), nullable=True),
    sa.Column('inflow_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_inflow_order_id'), 'orders', ['inflow_order_id'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('teams_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('webhook_url', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('changed_by', sa.String(), nullable=True),
    sa.Column('from_status', sa.String(), nullable=True),
    sa.Column('to_status', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_order_id'), 'audit_logs', ['order_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('teams_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('teams_message_id', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='notificationstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('webhook_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_notifications_order_id'), 'teams_notifications', ['order_id'], unique=False)
    op.create_index(op.f('ix_teams_notifications_status'), 'teams_notifications', ['status'], unique=False)
    op.create_index(op.f('ix_teams_notifications_teams_message_id'), 'teams_notifications', ['teams_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_notifications_teams_message_id'), table_name='teams_notifications')
    op.drop_index(op.f('ix_teams_notifications_status'), table_name='teams_notifications')
    op.drop_index(op.f('ix_teams_notifications_order_id'), table_name='teams_notifications')
    op.drop_table('teams_notifications')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_order_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('teams_config')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_inflow_order_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
